// This file is generated by scripts/generate-avatar-asset-bounds.py.
// Rerun after avatar layer PNGs are regenerated.

export interface AvatarAssetBoundsManifestEntry {
  naturalWidth: number;
  naturalHeight: number;
  left: number;
  top: number;
  width: number;
  height: number;
}

export const AVATAR_ASSET_BOUNDS_BY_URL: Record<string, AvatarAssetBoundsManifestEntry> = 
{
  "./public/images/avatar-layers/generated/normalized/Asset.Faces/Focused/Focused.Deep Brown.png": {
    "height": 330,
    "left": 372,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 136,
    "width": 352
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Faces/Focused/Focused.Fair.png": {
    "height": 330,
    "left": 372,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 136,
    "width": 352
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Faces/Focused/Focused.Medium Brown.png": {
    "height": 330,
    "left": 372,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 136,
    "width": 352
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Faces/Focused/Focused.Porcelain.png": {
    "height": 330,
    "left": 373,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 136,
    "width": 352
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Faces/Focused/Focused.Tan.png": {
    "height": 331,
    "left": 372,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 136,
    "width": 352
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Faces/Focused/Focused.Warm Beige.png": {
    "height": 330,
    "left": 372,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 136,
    "width": 352
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Faces/Focused/Focused.amber.png": {
    "height": 330,
    "left": 372,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 136,
    "width": 353
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Faces/Focused/Focused.golden.png": {
    "height": 330,
    "left": 372,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 136,
    "width": 352
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Faces/Happy/Happy.Fair.png": {
    "height": 330,
    "left": 373,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 136,
    "width": 352
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Faces/Happy/Happy.Porcelain.png": {
    "height": 330,
    "left": 373,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 136,
    "width": 352
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Faces/Happy/Happy.Warm beige.png": {
    "height": 331,
    "left": 373,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 136,
    "width": 352
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Faces/Happy/Happy.amber.png": {
    "height": 331,
    "left": 372,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 136,
    "width": 352
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Faces/Happy/Happy.golden.png": {
    "height": 331,
    "left": 372,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 136,
    "width": 353
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Faces/Happy/Happy.medium brown.png": {
    "height": 330,
    "left": 373,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 136,
    "width": 352
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Faces/Happy/Happy.tan.png": {
    "height": 330,
    "left": 373,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 136,
    "width": 352
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Faces/Happy/happy.deep brown.png": {
    "height": 330,
    "left": 373,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 136,
    "width": 352
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Faces/Surprise/Surprise.Fair.png": {
    "height": 330,
    "left": 373,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 136,
    "width": 352
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Faces/Surprise/Surprise.Porcelain.png": {
    "height": 330,
    "left": 373,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 136,
    "width": 352
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Faces/Surprise/Surprise.amber.png": {
    "height": 330,
    "left": 372,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 136,
    "width": 352
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Faces/Surprise/Surprise.deep brown.png": {
    "height": 330,
    "left": 372,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 136,
    "width": 352
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Faces/Surprise/Surprise.golden.png": {
    "height": 330,
    "left": 372,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 136,
    "width": 352
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Faces/Surprise/Surprise.medium brown.png": {
    "height": 330,
    "left": 372,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 136,
    "width": 352
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Faces/Surprise/Surprise.tan.png": {
    "height": 331,
    "left": 372,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 136,
    "width": 352
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Faces/Surprise/Surprise.warm beige.png": {
    "height": 331,
    "left": 373,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 136,
    "width": 351
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/Auburn/Bob.Auburn.png": {
    "height": 361,
    "left": 359,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 83,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/Auburn/Crop.Auburn.png": {
    "height": 387,
    "left": 359,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 82,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/Auburn/curls.Auburn.png": {
    "height": 531,
    "left": 369,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 83,
    "width": 360
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/Auburn/ponytail.Auburn.png": {
    "height": 410,
    "left": 338,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 104,
    "width": 420
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/Auburn/spikeslong.Auburn.png": {
    "height": 509,
    "left": 374,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 64,
    "width": 350
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/Auburn/spikesshort.auburn.png": {
    "height": 237,
    "left": 359,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 83,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/Auburn/swept.auburn.png": {
    "height": 364,
    "left": 359,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 83,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/black/Bob.black.png": {
    "height": 361,
    "left": 359,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 83,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/black/crop.black.png": {
    "height": 390,
    "left": 358,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 83,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/black/curls.black.png": {
    "height": 530,
    "left": 368,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 82,
    "width": 360
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/black/ponytail.black.png": {
    "height": 410,
    "left": 338,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 104,
    "width": 420
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/black/spikeslong.black.png": {
    "height": 513,
    "left": 374,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 64,
    "width": 350
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/black/spikesshort.black.png": {
    "height": 238,
    "left": 359,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 83,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/black/swept.black.png": {
    "height": 364,
    "left": 359,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 83,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/blonde/Bob.blonde.png": {
    "height": 364,
    "left": 359,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 82,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/blonde/crop.blonde.png": {
    "height": 389,
    "left": 359,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 83,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/blonde/curls.blonde.png": {
    "height": 529,
    "left": 369,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 83,
    "width": 360
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/blonde/ponytail.blonde.png": {
    "height": 410,
    "left": 338,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 104,
    "width": 420
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/blonde/spikeslong.blonde.png": {
    "height": 511,
    "left": 374,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 65,
    "width": 350
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/blonde/spikesshort.blonde.png": {
    "height": 238,
    "left": 359,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 83,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/blonde/swept.blonde.png": {
    "height": 364,
    "left": 358,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 83,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/brown/Bob.brown.png": {
    "height": 364,
    "left": 359,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 83,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/brown/crop.brown.png": {
    "height": 396,
    "left": 359,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 82,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/brown/curls.brown.png": {
    "height": 528,
    "left": 369,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 83,
    "width": 360
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/brown/ponytail.brown.png": {
    "height": 410,
    "left": 338,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 104,
    "width": 420
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/brown/spikeslong.brown.png": {
    "height": 510,
    "left": 374,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 65,
    "width": 350
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/brown/spikesshort.brown.png": {
    "height": 239,
    "left": 359,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 82,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/brown/swept.brown.png": {
    "height": 364,
    "left": 359,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 82,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/pink/bob.pink.png": {
    "height": 361,
    "left": 359,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 83,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/pink/crop.pink.png": {
    "height": 387,
    "left": 359,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 82,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/pink/curls.pink.png": {
    "height": 533,
    "left": 368,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 83,
    "width": 360
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/pink/ponytail.pink.png": {
    "height": 410,
    "left": 338,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 104,
    "width": 420
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/pink/spikeslong.pink.png": {
    "height": 512,
    "left": 373,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 65,
    "width": 350
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/pink/spikesshort.pink.png": {
    "height": 238,
    "left": 359,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 83,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/pink/swept.pink.png": {
    "height": 363,
    "left": 358,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 83,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/red/bob.red.png": {
    "height": 363,
    "left": 359,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 82,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/red/crop.red.png": {
    "height": 387,
    "left": 359,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 82,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/red/curls.red.png": {
    "height": 534,
    "left": 368,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 82,
    "width": 360
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/red/ponytail.red.png": {
    "height": 410,
    "left": 338,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 104,
    "width": 420
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/red/spikeslong.red.png": {
    "height": 511,
    "left": 374,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 64,
    "width": 350
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/red/spikesshort.red.png": {
    "height": 238,
    "left": 358,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 83,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/red/swept.red.png": {
    "height": 364,
    "left": 359,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 82,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/teal/bob.teal.png": {
    "height": 363,
    "left": 358,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 82,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/teal/crop.teal.png": {
    "height": 387,
    "left": 359,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 83,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/teal/curls.teal.png": {
    "height": 535,
    "left": 369,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 83,
    "width": 360
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/teal/ponytail.teal.png": {
    "height": 410,
    "left": 338,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 104,
    "width": 420
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/teal/spikeslong.teal.png": {
    "height": 510,
    "left": 374,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 65,
    "width": 350
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/teal/spikesshort.teal.png": {
    "height": 237,
    "left": 359,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 83,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair.front/teal/swept.teal.png": {
    "height": 363,
    "left": 359,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 82,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/Auburn/Bob.Auburn.png": {
    "height": 361,
    "left": 359,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 83,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/Auburn/Crop.Auburn.png": {
    "height": 387,
    "left": 359,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 82,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/Auburn/curls.Auburn.png": {
    "height": 531,
    "left": 369,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 83,
    "width": 360
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/Auburn/ponytail.Auburn.png": {
    "height": 411,
    "left": 338,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 104,
    "width": 420
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/Auburn/spikeslong.Auburn.png": {
    "height": 509,
    "left": 374,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 64,
    "width": 350
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/Auburn/spikesshort.auburn.png": {
    "height": 281,
    "left": 359,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 83,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/Auburn/swept.auburn.png": {
    "height": 364,
    "left": 359,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 83,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/black/Bob.black.png": {
    "height": 361,
    "left": 359,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 83,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/black/crop.black.png": {
    "height": 390,
    "left": 358,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 83,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/black/curls.black.png": {
    "height": 530,
    "left": 368,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 82,
    "width": 360
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/black/ponytail.black.png": {
    "height": 411,
    "left": 338,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 104,
    "width": 420
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/black/spikeslong.black.png": {
    "height": 513,
    "left": 374,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 64,
    "width": 350
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/black/spikesshort.black.png": {
    "height": 282,
    "left": 359,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 83,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/black/swept.black.png": {
    "height": 364,
    "left": 359,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 83,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/blonde/Bob.blonde.png": {
    "height": 364,
    "left": 359,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 82,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/blonde/crop.blonde.png": {
    "height": 389,
    "left": 359,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 83,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/blonde/curls.blonde.png": {
    "height": 529,
    "left": 369,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 83,
    "width": 360
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/blonde/ponytail.blonde.png": {
    "height": 411,
    "left": 338,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 104,
    "width": 420
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/blonde/spikeslong.blonde.png": {
    "height": 511,
    "left": 374,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 65,
    "width": 350
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/blonde/spikesshort.blonde.png": {
    "height": 283,
    "left": 359,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 83,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/blonde/swept.blonde.png": {
    "height": 364,
    "left": 358,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 83,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/brown/Bob.brown.png": {
    "height": 364,
    "left": 359,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 83,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/brown/crop.brown.png": {
    "height": 396,
    "left": 359,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 82,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/brown/curls.brown.png": {
    "height": 528,
    "left": 369,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 83,
    "width": 360
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/brown/ponytail.brown.png": {
    "height": 411,
    "left": 338,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 104,
    "width": 420
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/brown/spikeslong.brown.png": {
    "height": 510,
    "left": 374,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 65,
    "width": 350
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/brown/spikesshort.brown.png": {
    "height": 283,
    "left": 359,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 82,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/brown/swept.brown.png": {
    "height": 364,
    "left": 359,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 82,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/pink/bob.pink.png": {
    "height": 361,
    "left": 359,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 83,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/pink/crop.pink.png": {
    "height": 387,
    "left": 359,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 82,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/pink/curls.pink.png": {
    "height": 533,
    "left": 368,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 83,
    "width": 360
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/pink/ponytail.pink.png": {
    "height": 411,
    "left": 338,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 104,
    "width": 420
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/pink/spikeslong.pink.png": {
    "height": 512,
    "left": 373,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 65,
    "width": 350
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/pink/spikesshort.pink.png": {
    "height": 282,
    "left": 359,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 83,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/pink/swept.pink.png": {
    "height": 363,
    "left": 358,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 83,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/red/bob.red.png": {
    "height": 363,
    "left": 359,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 82,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/red/crop.red.png": {
    "height": 387,
    "left": 359,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 82,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/red/curls.red.png": {
    "height": 534,
    "left": 368,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 82,
    "width": 360
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/red/ponytail.red.png": {
    "height": 411,
    "left": 338,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 104,
    "width": 420
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/red/spikeslong.red.png": {
    "height": 511,
    "left": 374,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 64,
    "width": 350
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/red/spikesshort.red.png": {
    "height": 283,
    "left": 358,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 83,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/red/swept.red.png": {
    "height": 364,
    "left": 358,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 82,
    "width": 381
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/teal/bob.teal.png": {
    "height": 363,
    "left": 358,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 82,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/teal/crop.teal.png": {
    "height": 387,
    "left": 359,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 83,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/teal/curls.teal.png": {
    "height": 535,
    "left": 369,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 83,
    "width": 360
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/teal/ponytail.teal.png": {
    "height": 411,
    "left": 338,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 104,
    "width": 420
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/teal/spikeslong.teal.png": {
    "height": 510,
    "left": 374,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 65,
    "width": 350
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/teal/spikesshort.teal.png": {
    "height": 281,
    "left": 359,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 83,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.Hair/teal/swept.teal.png": {
    "height": 363,
    "left": 359,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 82,
    "width": 380
  },
  "./public/images/avatar-layers/generated/normalized/Asset.outfit/Outfit. Explorers Jacket.png": {
    "height": 1000,
    "left": 183,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 320,
    "width": 732
  },
  "./public/images/avatar-layers/generated/normalized/Asset.outfit/Outfit.Archivist Vest.png": {
    "height": 1000,
    "left": 240,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 321,
    "width": 618
  },
  "./public/images/avatar-layers/generated/normalized/Asset.outfit/Outfit.Artist apron.png": {
    "height": 1000,
    "left": 174,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 320,
    "width": 750
  },
  "./public/images/avatar-layers/generated/normalized/Asset.outfit/Outfit.Dream Painter.png": {
    "height": 1000,
    "left": 192,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 321,
    "width": 714
  },
  "./public/images/avatar-layers/generated/normalized/Asset.outfit/Outfit.Explorer.png": {
    "height": 1000,
    "left": 229,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 320,
    "width": 640
  },
  "./public/images/avatar-layers/generated/normalized/Asset.outfit/Outfit.Gallery Guard.png": {
    "height": 1000,
    "left": 187,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 320,
    "width": 724
  },
  "./public/images/avatar-layers/generated/normalized/Asset.outfit/Outfit.Herbologist.png": {
    "height": 1000,
    "left": 232,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 320,
    "width": 634
  },
  "./public/images/avatar-layers/generated/normalized/Asset.outfit/Outfit.Inventors apron.png": {
    "height": 1000,
    "left": 189,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 320,
    "width": 720
  },
  "./public/images/avatar-layers/generated/normalized/Asset.outfit/Outfit.Magic Explorer.png": {
    "height": 1001,
    "left": 208,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 319,
    "width": 683
  },
  "./public/images/avatar-layers/generated/normalized/Asset.outfit/Outfit.Masonry overalls.png": {
    "height": 1000,
    "left": 210,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 320,
    "width": 679
  },
  "./public/images/avatar-layers/generated/normalized/Asset.outfit/Outfit.Mystic Robe.png": {
    "height": 1001,
    "left": 175,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 320,
    "width": 743
  },
  "./public/images/avatar-layers/generated/normalized/Asset.outfit/Outfit.Painted Hoodie.png": {
    "height": 1000,
    "left": 227,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 321,
    "width": 644
  },
  "./public/images/avatar-layers/generated/normalized/Asset.outfit/Outfit.Painters smock.png": {
    "height": 1000,
    "left": 218,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 320,
    "width": 661
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/amber.png": {
    "height": 440,
    "left": 164,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 430,
    "width": 740
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/archivist_vest/lower_hand/amber.png": {
    "height": 84,
    "left": 255,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 704,
    "width": 70
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/archivist_vest/lower_hand/deep_brown.png": {
    "height": 84,
    "left": 255,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 704,
    "width": 70
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/archivist_vest/lower_hand/fair.png": {
    "height": 84,
    "left": 255,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 704,
    "width": 70
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/archivist_vest/lower_hand/golden.png": {
    "height": 84,
    "left": 255,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 704,
    "width": 70
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/archivist_vest/lower_hand/medium_brown.png": {
    "height": 84,
    "left": 255,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 704,
    "width": 70
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/archivist_vest/lower_hand/porcelain.png": {
    "height": 84,
    "left": 255,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 704,
    "width": 70
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/archivist_vest/lower_hand/tan.png": {
    "height": 84,
    "left": 255,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 704,
    "width": 70
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/archivist_vest/lower_hand/warm_beige.png": {
    "height": 84,
    "left": 255,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 704,
    "width": 70
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/archivist_vest/raised_hand/amber.png": {
    "height": 101,
    "left": 770,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 490,
    "width": 73
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/archivist_vest/raised_hand/deep_brown.png": {
    "height": 101,
    "left": 770,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 490,
    "width": 73
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/archivist_vest/raised_hand/fair.png": {
    "height": 101,
    "left": 770,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 490,
    "width": 73
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/archivist_vest/raised_hand/golden.png": {
    "height": 101,
    "left": 770,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 490,
    "width": 73
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/archivist_vest/raised_hand/medium_brown.png": {
    "height": 101,
    "left": 770,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 490,
    "width": 73
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/archivist_vest/raised_hand/porcelain.png": {
    "height": 101,
    "left": 770,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 490,
    "width": 73
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/archivist_vest/raised_hand/tan.png": {
    "height": 101,
    "left": 770,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 490,
    "width": 73
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/archivist_vest/raised_hand/warm_beige.png": {
    "height": 101,
    "left": 770,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 490,
    "width": 73
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/artist_apron/lower_hand/amber.png": {
    "height": 103,
    "left": 195,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 755,
    "width": 95
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/artist_apron/lower_hand/deep_brown.png": {
    "height": 103,
    "left": 195,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 755,
    "width": 95
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/artist_apron/lower_hand/fair.png": {
    "height": 103,
    "left": 195,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 755,
    "width": 95
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/artist_apron/lower_hand/golden.png": {
    "height": 103,
    "left": 195,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 755,
    "width": 95
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/artist_apron/lower_hand/medium_brown.png": {
    "height": 103,
    "left": 195,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 755,
    "width": 95
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/artist_apron/lower_hand/porcelain.png": {
    "height": 103,
    "left": 195,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 755,
    "width": 95
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/artist_apron/lower_hand/tan.png": {
    "height": 103,
    "left": 195,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 755,
    "width": 95
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/artist_apron/lower_hand/warm_beige.png": {
    "height": 103,
    "left": 195,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 755,
    "width": 95
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/artist_apron/raised_hand/amber.png": {
    "height": 126,
    "left": 811,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 519,
    "width": 92
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/artist_apron/raised_hand/deep_brown.png": {
    "height": 126,
    "left": 811,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 519,
    "width": 92
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/artist_apron/raised_hand/fair.png": {
    "height": 126,
    "left": 811,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 519,
    "width": 92
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/artist_apron/raised_hand/golden.png": {
    "height": 126,
    "left": 811,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 519,
    "width": 92
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/artist_apron/raised_hand/medium_brown.png": {
    "height": 126,
    "left": 811,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 519,
    "width": 92
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/artist_apron/raised_hand/porcelain.png": {
    "height": 126,
    "left": 811,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 519,
    "width": 92
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/artist_apron/raised_hand/tan.png": {
    "height": 126,
    "left": 811,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 519,
    "width": 92
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/artist_apron/raised_hand/warm_beige.png": {
    "height": 126,
    "left": 811,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 519,
    "width": 92
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/dream_painter/lower_hand/amber.png": {
    "height": 82,
    "left": 209,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 777,
    "width": 79
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/dream_painter/lower_hand/deep_brown.png": {
    "height": 82,
    "left": 209,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 777,
    "width": 79
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/dream_painter/lower_hand/fair.png": {
    "height": 82,
    "left": 209,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 777,
    "width": 79
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/dream_painter/lower_hand/golden.png": {
    "height": 82,
    "left": 209,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 777,
    "width": 79
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/dream_painter/lower_hand/medium_brown.png": {
    "height": 82,
    "left": 209,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 777,
    "width": 79
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/dream_painter/lower_hand/porcelain.png": {
    "height": 82,
    "left": 209,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 777,
    "width": 79
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/dream_painter/lower_hand/tan.png": {
    "height": 82,
    "left": 209,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 777,
    "width": 79
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/dream_painter/lower_hand/warm_beige.png": {
    "height": 82,
    "left": 209,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 777,
    "width": 79
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/dream_painter/raised_hand/amber.png": {
    "height": 96,
    "left": 818,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 528,
    "width": 73
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/dream_painter/raised_hand/deep_brown.png": {
    "height": 96,
    "left": 818,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 528,
    "width": 73
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/dream_painter/raised_hand/fair.png": {
    "height": 96,
    "left": 818,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 528,
    "width": 73
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/dream_painter/raised_hand/golden.png": {
    "height": 96,
    "left": 818,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 528,
    "width": 73
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/dream_painter/raised_hand/medium_brown.png": {
    "height": 96,
    "left": 818,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 528,
    "width": 73
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/dream_painter/raised_hand/porcelain.png": {
    "height": 96,
    "left": 818,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 528,
    "width": 73
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/dream_painter/raised_hand/tan.png": {
    "height": 96,
    "left": 818,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 528,
    "width": 73
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/dream_painter/raised_hand/warm_beige.png": {
    "height": 96,
    "left": 818,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 528,
    "width": 73
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/explorer/lower_hand/amber.png": {
    "height": 101,
    "left": 248,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 746,
    "width": 85
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/explorer/lower_hand/deep_brown.png": {
    "height": 101,
    "left": 248,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 746,
    "width": 85
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/explorer/lower_hand/fair.png": {
    "height": 101,
    "left": 248,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 746,
    "width": 85
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/explorer/lower_hand/golden.png": {
    "height": 101,
    "left": 248,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 746,
    "width": 85
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/explorer/lower_hand/medium_brown.png": {
    "height": 101,
    "left": 248,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 746,
    "width": 85
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/explorer/lower_hand/porcelain.png": {
    "height": 101,
    "left": 248,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 746,
    "width": 85
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/explorer/lower_hand/tan.png": {
    "height": 101,
    "left": 248,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 746,
    "width": 85
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/explorer/lower_hand/warm_beige.png": {
    "height": 101,
    "left": 248,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 746,
    "width": 85
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/explorer/raised_hand/amber.png": {
    "height": 72,
    "left": 818,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 588,
    "width": 32
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/explorer/raised_hand/deep_brown.png": {
    "height": 72,
    "left": 818,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 588,
    "width": 32
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/explorer/raised_hand/fair.png": {
    "height": 72,
    "left": 818,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 588,
    "width": 32
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/explorer/raised_hand/golden.png": {
    "height": 72,
    "left": 818,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 588,
    "width": 32
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/explorer/raised_hand/medium_brown.png": {
    "height": 72,
    "left": 818,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 588,
    "width": 32
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/explorer/raised_hand/porcelain.png": {
    "height": 72,
    "left": 818,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 588,
    "width": 32
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/explorer/raised_hand/tan.png": {
    "height": 72,
    "left": 818,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 588,
    "width": 32
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/explorer/raised_hand/warm_beige.png": {
    "height": 72,
    "left": 818,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 588,
    "width": 32
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/gallery_guard/lower_hand/amber.png": {
    "height": 104,
    "left": 203,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 769,
    "width": 86
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/gallery_guard/lower_hand/deep_brown.png": {
    "height": 104,
    "left": 203,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 769,
    "width": 86
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/gallery_guard/lower_hand/fair.png": {
    "height": 104,
    "left": 203,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 769,
    "width": 86
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/gallery_guard/lower_hand/golden.png": {
    "height": 104,
    "left": 203,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 769,
    "width": 86
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/gallery_guard/lower_hand/medium_brown.png": {
    "height": 104,
    "left": 203,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 769,
    "width": 86
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/gallery_guard/lower_hand/porcelain.png": {
    "height": 104,
    "left": 203,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 769,
    "width": 86
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/gallery_guard/lower_hand/tan.png": {
    "height": 104,
    "left": 203,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 769,
    "width": 86
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/gallery_guard/lower_hand/warm_beige.png": {
    "height": 104,
    "left": 203,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 769,
    "width": 86
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/gallery_guard/raised_hand/amber.png": {
    "height": 96,
    "left": 811,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 482,
    "width": 84
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/gallery_guard/raised_hand/deep_brown.png": {
    "height": 96,
    "left": 811,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 482,
    "width": 84
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/gallery_guard/raised_hand/fair.png": {
    "height": 96,
    "left": 811,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 482,
    "width": 84
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/gallery_guard/raised_hand/golden.png": {
    "height": 96,
    "left": 811,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 482,
    "width": 84
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/gallery_guard/raised_hand/medium_brown.png": {
    "height": 96,
    "left": 811,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 482,
    "width": 84
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/gallery_guard/raised_hand/porcelain.png": {
    "height": 96,
    "left": 811,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 482,
    "width": 84
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/gallery_guard/raised_hand/tan.png": {
    "height": 96,
    "left": 811,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 482,
    "width": 84
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/gallery_guard/raised_hand/warm_beige.png": {
    "height": 96,
    "left": 811,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 482,
    "width": 84
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/herbologist/lower_hand/amber.png": {
    "height": 93,
    "left": 247,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 690,
    "width": 75
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/herbologist/lower_hand/deep_brown.png": {
    "height": 93,
    "left": 247,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 690,
    "width": 75
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/herbologist/lower_hand/fair.png": {
    "height": 93,
    "left": 247,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 690,
    "width": 75
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/herbologist/lower_hand/golden.png": {
    "height": 93,
    "left": 247,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 690,
    "width": 75
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/herbologist/lower_hand/medium_brown.png": {
    "height": 93,
    "left": 247,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 690,
    "width": 75
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/herbologist/lower_hand/porcelain.png": {
    "height": 93,
    "left": 247,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 690,
    "width": 75
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/herbologist/lower_hand/tan.png": {
    "height": 93,
    "left": 247,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 690,
    "width": 75
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/herbologist/lower_hand/warm_beige.png": {
    "height": 93,
    "left": 247,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 690,
    "width": 75
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/herbologist/raised_hand/amber.png": {
    "height": 105,
    "left": 782,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 490,
    "width": 69
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/herbologist/raised_hand/deep_brown.png": {
    "height": 105,
    "left": 782,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 490,
    "width": 69
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/herbologist/raised_hand/fair.png": {
    "height": 105,
    "left": 782,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 490,
    "width": 69
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/herbologist/raised_hand/golden.png": {
    "height": 105,
    "left": 782,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 490,
    "width": 69
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/herbologist/raised_hand/medium_brown.png": {
    "height": 105,
    "left": 782,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 490,
    "width": 69
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/herbologist/raised_hand/porcelain.png": {
    "height": 105,
    "left": 782,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 490,
    "width": 69
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/herbologist/raised_hand/tan.png": {
    "height": 105,
    "left": 782,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 490,
    "width": 69
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/herbologist/raised_hand/warm_beige.png": {
    "height": 105,
    "left": 782,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 490,
    "width": 69
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/inventors_apron/lower_hand/amber.png": {
    "height": 102,
    "left": 206,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 720,
    "width": 103
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/inventors_apron/lower_hand/deep_brown.png": {
    "height": 102,
    "left": 206,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 720,
    "width": 103
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/inventors_apron/lower_hand/fair.png": {
    "height": 102,
    "left": 206,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 720,
    "width": 103
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/inventors_apron/lower_hand/golden.png": {
    "height": 102,
    "left": 206,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 720,
    "width": 103
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/inventors_apron/lower_hand/medium_brown.png": {
    "height": 102,
    "left": 206,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 720,
    "width": 103
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/inventors_apron/lower_hand/porcelain.png": {
    "height": 102,
    "left": 206,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 720,
    "width": 103
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/inventors_apron/lower_hand/tan.png": {
    "height": 102,
    "left": 206,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 720,
    "width": 103
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/inventors_apron/lower_hand/warm_beige.png": {
    "height": 102,
    "left": 206,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 720,
    "width": 103
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/inventors_apron/raised_hand/amber.png": {
    "height": 105,
    "left": 817,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 462,
    "width": 74
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/inventors_apron/raised_hand/deep_brown.png": {
    "height": 105,
    "left": 817,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 462,
    "width": 74
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/inventors_apron/raised_hand/fair.png": {
    "height": 105,
    "left": 817,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 462,
    "width": 74
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/inventors_apron/raised_hand/golden.png": {
    "height": 105,
    "left": 817,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 462,
    "width": 74
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/inventors_apron/raised_hand/medium_brown.png": {
    "height": 105,
    "left": 817,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 462,
    "width": 74
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/inventors_apron/raised_hand/porcelain.png": {
    "height": 105,
    "left": 817,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 462,
    "width": 74
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/inventors_apron/raised_hand/tan.png": {
    "height": 105,
    "left": 817,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 462,
    "width": 74
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/inventors_apron/raised_hand/warm_beige.png": {
    "height": 105,
    "left": 817,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 462,
    "width": 74
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/magic_explorer/lower_hand/amber.png": {
    "height": 95,
    "left": 222,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 760,
    "width": 74
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/magic_explorer/lower_hand/deep_brown.png": {
    "height": 95,
    "left": 222,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 760,
    "width": 74
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/magic_explorer/lower_hand/fair.png": {
    "height": 95,
    "left": 222,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 760,
    "width": 74
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/magic_explorer/lower_hand/golden.png": {
    "height": 95,
    "left": 222,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 760,
    "width": 74
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/magic_explorer/lower_hand/medium_brown.png": {
    "height": 95,
    "left": 222,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 760,
    "width": 74
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/magic_explorer/lower_hand/porcelain.png": {
    "height": 95,
    "left": 222,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 760,
    "width": 74
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/magic_explorer/lower_hand/tan.png": {
    "height": 95,
    "left": 222,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 760,
    "width": 74
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/magic_explorer/lower_hand/warm_beige.png": {
    "height": 95,
    "left": 222,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 760,
    "width": 74
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/magic_explorer/raised_hand/amber.png": {
    "height": 82,
    "left": 796,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 516,
    "width": 80
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/magic_explorer/raised_hand/deep_brown.png": {
    "height": 82,
    "left": 796,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 516,
    "width": 80
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/magic_explorer/raised_hand/fair.png": {
    "height": 82,
    "left": 796,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 516,
    "width": 80
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/magic_explorer/raised_hand/golden.png": {
    "height": 82,
    "left": 796,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 516,
    "width": 80
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/magic_explorer/raised_hand/medium_brown.png": {
    "height": 82,
    "left": 796,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 516,
    "width": 80
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/magic_explorer/raised_hand/porcelain.png": {
    "height": 82,
    "left": 796,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 516,
    "width": 80
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/magic_explorer/raised_hand/tan.png": {
    "height": 82,
    "left": 796,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 516,
    "width": 80
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/magic_explorer/raised_hand/warm_beige.png": {
    "height": 82,
    "left": 796,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 516,
    "width": 80
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/masonry_overalls/lower_hand/amber.png": {
    "height": 118,
    "left": 229,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 695,
    "width": 93
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/masonry_overalls/lower_hand/deep_brown.png": {
    "height": 118,
    "left": 229,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 695,
    "width": 93
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/masonry_overalls/lower_hand/fair.png": {
    "height": 118,
    "left": 229,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 695,
    "width": 93
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/masonry_overalls/lower_hand/golden.png": {
    "height": 118,
    "left": 229,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 695,
    "width": 93
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/masonry_overalls/lower_hand/medium_brown.png": {
    "height": 118,
    "left": 229,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 695,
    "width": 93
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/masonry_overalls/lower_hand/porcelain.png": {
    "height": 118,
    "left": 229,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 695,
    "width": 93
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/masonry_overalls/lower_hand/tan.png": {
    "height": 118,
    "left": 229,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 695,
    "width": 93
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/masonry_overalls/lower_hand/warm_beige.png": {
    "height": 118,
    "left": 229,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 695,
    "width": 93
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/masonry_overalls/raised_hand/amber.png": {
    "height": 127,
    "left": 791,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 506,
    "width": 80
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/masonry_overalls/raised_hand/deep_brown.png": {
    "height": 127,
    "left": 791,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 506,
    "width": 80
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/masonry_overalls/raised_hand/fair.png": {
    "height": 127,
    "left": 791,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 506,
    "width": 80
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/masonry_overalls/raised_hand/golden.png": {
    "height": 127,
    "left": 791,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 506,
    "width": 80
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/masonry_overalls/raised_hand/medium_brown.png": {
    "height": 127,
    "left": 791,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 506,
    "width": 80
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/masonry_overalls/raised_hand/porcelain.png": {
    "height": 127,
    "left": 791,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 506,
    "width": 80
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/masonry_overalls/raised_hand/tan.png": {
    "height": 127,
    "left": 791,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 506,
    "width": 80
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/masonry_overalls/raised_hand/warm_beige.png": {
    "height": 127,
    "left": 791,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 506,
    "width": 80
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/mystic_robe/lower_hand/amber.png": {
    "height": 97,
    "left": 191,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 772,
    "width": 85
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/mystic_robe/lower_hand/deep_brown.png": {
    "height": 97,
    "left": 191,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 772,
    "width": 85
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/mystic_robe/lower_hand/fair.png": {
    "height": 97,
    "left": 191,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 772,
    "width": 85
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/mystic_robe/lower_hand/golden.png": {
    "height": 97,
    "left": 191,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 772,
    "width": 85
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/mystic_robe/lower_hand/medium_brown.png": {
    "height": 97,
    "left": 191,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 772,
    "width": 85
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/mystic_robe/lower_hand/porcelain.png": {
    "height": 97,
    "left": 191,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 772,
    "width": 85
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/mystic_robe/lower_hand/tan.png": {
    "height": 97,
    "left": 191,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 772,
    "width": 85
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/mystic_robe/lower_hand/warm_beige.png": {
    "height": 97,
    "left": 191,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 772,
    "width": 85
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/mystic_robe/raised_hand/amber.png": {
    "height": 101,
    "left": 822,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 533,
    "width": 80
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/mystic_robe/raised_hand/deep_brown.png": {
    "height": 101,
    "left": 822,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 533,
    "width": 80
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/mystic_robe/raised_hand/fair.png": {
    "height": 101,
    "left": 822,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 533,
    "width": 80
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/mystic_robe/raised_hand/golden.png": {
    "height": 101,
    "left": 822,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 533,
    "width": 80
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/mystic_robe/raised_hand/medium_brown.png": {
    "height": 101,
    "left": 822,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 533,
    "width": 80
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/mystic_robe/raised_hand/porcelain.png": {
    "height": 101,
    "left": 822,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 533,
    "width": 80
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/mystic_robe/raised_hand/tan.png": {
    "height": 101,
    "left": 822,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 533,
    "width": 80
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/mystic_robe/raised_hand/warm_beige.png": {
    "height": 101,
    "left": 822,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 533,
    "width": 80
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/painted_hoodie/lower_hand/amber.png": {
    "height": 94,
    "left": 245,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 806,
    "width": 86
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/painted_hoodie/lower_hand/deep_brown.png": {
    "height": 94,
    "left": 245,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 806,
    "width": 86
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/painted_hoodie/lower_hand/fair.png": {
    "height": 94,
    "left": 245,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 806,
    "width": 86
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/painted_hoodie/lower_hand/golden.png": {
    "height": 94,
    "left": 245,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 806,
    "width": 86
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/painted_hoodie/lower_hand/medium_brown.png": {
    "height": 94,
    "left": 245,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 806,
    "width": 86
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/painted_hoodie/lower_hand/porcelain.png": {
    "height": 94,
    "left": 245,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 806,
    "width": 86
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/painted_hoodie/lower_hand/tan.png": {
    "height": 94,
    "left": 245,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 806,
    "width": 86
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/painted_hoodie/lower_hand/warm_beige.png": {
    "height": 94,
    "left": 245,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 806,
    "width": 86
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/painted_hoodie/raised_hand/amber.png": {
    "height": 83,
    "left": 802,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 607,
    "width": 51
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/painted_hoodie/raised_hand/deep_brown.png": {
    "height": 83,
    "left": 802,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 607,
    "width": 51
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/painted_hoodie/raised_hand/fair.png": {
    "height": 83,
    "left": 802,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 607,
    "width": 51
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/painted_hoodie/raised_hand/golden.png": {
    "height": 83,
    "left": 802,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 607,
    "width": 51
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/painted_hoodie/raised_hand/medium_brown.png": {
    "height": 83,
    "left": 802,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 607,
    "width": 51
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/painted_hoodie/raised_hand/porcelain.png": {
    "height": 83,
    "left": 802,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 607,
    "width": 51
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/painted_hoodie/raised_hand/tan.png": {
    "height": 83,
    "left": 802,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 607,
    "width": 51
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/painted_hoodie/raised_hand/warm_beige.png": {
    "height": 83,
    "left": 802,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 607,
    "width": 51
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/painters_smock/lower_hand/amber.png": {
    "height": 92,
    "left": 234,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 757,
    "width": 72
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/painters_smock/lower_hand/deep_brown.png": {
    "height": 92,
    "left": 234,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 757,
    "width": 72
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/painters_smock/lower_hand/fair.png": {
    "height": 92,
    "left": 234,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 757,
    "width": 72
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/painters_smock/lower_hand/golden.png": {
    "height": 92,
    "left": 234,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 757,
    "width": 72
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/painters_smock/lower_hand/medium_brown.png": {
    "height": 92,
    "left": 234,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 757,
    "width": 72
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/painters_smock/lower_hand/porcelain.png": {
    "height": 92,
    "left": 234,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 757,
    "width": 72
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/painters_smock/lower_hand/tan.png": {
    "height": 92,
    "left": 234,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 757,
    "width": 72
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/painters_smock/lower_hand/warm_beige.png": {
    "height": 92,
    "left": 234,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 757,
    "width": 72
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/painters_smock/raised_hand/amber.png": {
    "height": 114,
    "left": 779,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 489,
    "width": 84
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/painters_smock/raised_hand/deep_brown.png": {
    "height": 114,
    "left": 779,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 489,
    "width": 84
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/painters_smock/raised_hand/fair.png": {
    "height": 114,
    "left": 779,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 489,
    "width": 84
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/painters_smock/raised_hand/golden.png": {
    "height": 114,
    "left": 779,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 489,
    "width": 84
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/painters_smock/raised_hand/medium_brown.png": {
    "height": 114,
    "left": 779,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 489,
    "width": 84
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/painters_smock/raised_hand/porcelain.png": {
    "height": 114,
    "left": 779,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 489,
    "width": 84
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/painters_smock/raised_hand/tan.png": {
    "height": 114,
    "left": 779,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 489,
    "width": 84
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/by_outfit/painters_smock/raised_hand/warm_beige.png": {
    "height": 114,
    "left": 779,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 489,
    "width": 84
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/deep_brown.png": {
    "height": 440,
    "left": 164,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 430,
    "width": 740
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/fair.png": {
    "height": 440,
    "left": 164,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 430,
    "width": 740
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/golden.png": {
    "height": 440,
    "left": 164,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 430,
    "width": 740
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/hands/amber.png": {
    "height": 292,
    "left": 164,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 578,
    "width": 740
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/hands/deep_brown.png": {
    "height": 292,
    "left": 164,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 578,
    "width": 740
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/hands/fair.png": {
    "height": 292,
    "left": 164,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 578,
    "width": 740
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/hands/golden.png": {
    "height": 292,
    "left": 164,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 578,
    "width": 740
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/hands/medium_brown.png": {
    "height": 292,
    "left": 164,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 578,
    "width": 740
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/hands/porcelain.png": {
    "height": 292,
    "left": 164,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 578,
    "width": 740
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/hands/tan.png": {
    "height": 292,
    "left": 164,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 578,
    "width": 740
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/hands/warm_beige.png": {
    "height": 292,
    "left": 164,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 578,
    "width": 740
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/lower_hand/amber.png": {
    "height": 80,
    "left": 164,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 790,
    "width": 76
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/lower_hand/deep_brown.png": {
    "height": 80,
    "left": 164,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 790,
    "width": 76
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/lower_hand/fair.png": {
    "height": 80,
    "left": 164,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 790,
    "width": 76
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/lower_hand/golden.png": {
    "height": 80,
    "left": 164,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 790,
    "width": 76
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/lower_hand/medium_brown.png": {
    "height": 80,
    "left": 164,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 790,
    "width": 76
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/lower_hand/porcelain.png": {
    "height": 80,
    "left": 164,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 790,
    "width": 76
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/lower_hand/tan.png": {
    "height": 80,
    "left": 164,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 790,
    "width": 76
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/lower_hand/warm_beige.png": {
    "height": 80,
    "left": 164,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 790,
    "width": 76
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/medium_brown.png": {
    "height": 440,
    "left": 164,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 430,
    "width": 740
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/neck/amber.png": {
    "height": 70,
    "left": 512,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 430,
    "width": 42
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/neck/deep_brown.png": {
    "height": 70,
    "left": 512,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 430,
    "width": 42
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/neck/fair.png": {
    "height": 70,
    "left": 512,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 430,
    "width": 42
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/neck/golden.png": {
    "height": 70,
    "left": 512,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 430,
    "width": 42
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/neck/medium_brown.png": {
    "height": 70,
    "left": 512,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 430,
    "width": 42
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/neck/porcelain.png": {
    "height": 70,
    "left": 512,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 430,
    "width": 42
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/neck/tan.png": {
    "height": 70,
    "left": 512,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 430,
    "width": 42
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/neck/warm_beige.png": {
    "height": 70,
    "left": 512,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 430,
    "width": 42
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/porcelain.png": {
    "height": 440,
    "left": 164,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 430,
    "width": 740
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/raised_hand/amber.png": {
    "height": 82,
    "left": 820,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 578,
    "width": 84
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/raised_hand/deep_brown.png": {
    "height": 82,
    "left": 820,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 578,
    "width": 84
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/raised_hand/fair.png": {
    "height": 82,
    "left": 820,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 578,
    "width": 84
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/raised_hand/golden.png": {
    "height": 82,
    "left": 820,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 578,
    "width": 84
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/raised_hand/medium_brown.png": {
    "height": 82,
    "left": 820,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 578,
    "width": 84
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/raised_hand/porcelain.png": {
    "height": 82,
    "left": 820,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 578,
    "width": 84
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/raised_hand/tan.png": {
    "height": 82,
    "left": 820,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 578,
    "width": 84
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/raised_hand/warm_beige.png": {
    "height": 82,
    "left": 820,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 578,
    "width": 84
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/tan.png": {
    "height": 440,
    "left": 164,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 430,
    "width": 740
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/under/amber.png": {
    "height": 70,
    "left": 512,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 430,
    "width": 42
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/under/deep_brown.png": {
    "height": 70,
    "left": 512,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 430,
    "width": 42
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/under/fair.png": {
    "height": 70,
    "left": 512,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 430,
    "width": 42
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/under/golden.png": {
    "height": 70,
    "left": 512,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 430,
    "width": 42
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/under/medium_brown.png": {
    "height": 70,
    "left": 512,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 430,
    "width": 42
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/under/porcelain.png": {
    "height": 70,
    "left": 512,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 430,
    "width": 42
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/under/tan.png": {
    "height": 70,
    "left": 512,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 430,
    "width": 42
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/under/warm_beige.png": {
    "height": 70,
    "left": 512,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 430,
    "width": 42
  },
  "./public/images/avatar-layers/generated/normalized/Asset.skin/warm_beige.png": {
    "height": 440,
    "left": 164,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 430,
    "width": 740
  },
  "./public/images/avatar-layers/generated/normalized/asset.object/object.brush.png": {
    "height": 430,
    "left": 760,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 451,
    "width": 211
  },
  "./public/images/avatar-layers/generated/normalized/asset.object/object.camera.png": {
    "height": 208,
    "left": 716,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 547,
    "width": 280
  },
  "./public/images/avatar-layers/generated/normalized/asset.object/object.coinpouch.png": {
    "height": 380,
    "left": 726,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 477,
    "width": 282
  },
  "./public/images/avatar-layers/generated/normalized/asset.object/object.compass.png": {
    "height": 352,
    "left": 726,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 489,
    "width": 280
  },
  "./public/images/avatar-layers/generated/normalized/asset.object/object.crystal.png": {
    "height": 430,
    "left": 762,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 451,
    "width": 209
  },
  "./public/images/avatar-layers/generated/normalized/asset.object/object.crystalstaff.png": {
    "height": 700,
    "left": 814,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 411,
    "width": 93
  },
  "./public/images/avatar-layers/generated/normalized/asset.object/object.flower.png": {
    "height": 561,
    "left": 776,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 420,
    "width": 180
  },
  "./public/images/avatar-layers/generated/normalized/asset.object/object.herb.png": {
    "height": 430,
    "left": 767,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 451,
    "width": 197
  },
  "./public/images/avatar-layers/generated/normalized/asset.object/object.hourglass.png": {
    "height": 430,
    "left": 742,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 450,
    "width": 247
  },
  "./public/images/avatar-layers/generated/normalized/asset.object/object.key.png": {
    "height": 400,
    "left": 726,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 466,
    "width": 280
  },
  "./public/images/avatar-layers/generated/normalized/asset.object/object.magnifying glass.png": {
    "height": 430,
    "left": 752,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 451,
    "width": 227
  },
  "./public/images/avatar-layers/generated/normalized/asset.object/object.mallet.png": {
    "height": 425,
    "left": 725,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 454,
    "width": 280
  },
  "./public/images/avatar-layers/generated/normalized/asset.object/object.map.png": {
    "height": 208,
    "left": 715,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 547,
    "width": 280
  },
  "./public/images/avatar-layers/generated/normalized/asset.object/object.palette.png": {
    "height": 250,
    "left": 720,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 526,
    "width": 272
  },
  "./public/images/avatar-layers/generated/normalized/asset.object/object.pencil.png": {
    "height": 430,
    "left": 727,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 451,
    "width": 277
  },
  "./public/images/avatar-layers/generated/normalized/asset.object/object.potion.png": {
    "height": 431,
    "left": 727,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 450,
    "width": 277
  },
  "./public/images/avatar-layers/generated/normalized/asset.object/object.quill.png": {
    "height": 430,
    "left": 761,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 451,
    "width": 210
  },
  "./public/images/avatar-layers/generated/normalized/asset.object/object.scroll.png": {
    "height": 560,
    "left": 784,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 421,
    "width": 164
  },
  "./public/images/avatar-layers/generated/normalized/asset.object/object.shield.png": {
    "height": 328,
    "left": 726,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 501,
    "width": 280
  },
  "./public/images/avatar-layers/generated/normalized/asset.object/object.spellbook.png": {
    "height": 400,
    "left": 725,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 466,
    "width": 280
  },
  "./public/images/avatar-layers/generated/normalized/asset.object/object.starstaff.png": {
    "height": 700,
    "left": 812,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 411,
    "width": 97
  },
  "./public/images/avatar-layers/generated/normalized/asset.object/object.telescope.png": {
    "height": 250,
    "left": 716,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 526,
    "width": 280
  },
  "./public/images/avatar-layers/generated/normalized/asset.object/object.torch.png": {
    "height": 700,
    "left": 800,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 411,
    "width": 121
  },
  "./public/images/avatar-layers/generated/normalized/asset.object/object.wand.png": {
    "height": 430,
    "left": 751,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 451,
    "width": 230
  },
  "./public/images/avatar-layers/generated/normalized/asset.object/object.wrench.png": {
    "height": 695,
    "left": 775,
    "naturalHeight": 1536,
    "naturalWidth": 1024,
    "top": 414,
    "width": 170
  }
}
;
