// This file is generated by scripts/generate-avatar-layer-manifest.mjs.
// Edit files in public/images/avatar-layers/source, then rerun npm run avatar:manifest.

export const GENERATED_AVATAR_SKIN_TONES = [
  {
    "id": "amber",
    "name": "Amber",
    "color": "#d97706",
    "shadow": "#855136",
    "highlight": "#ffd0ac"
  },
  {
    "id": "deep_brown",
    "name": "Deep Brown",
    "color": "#5f3324",
    "shadow": "#855136",
    "highlight": "#ffd0ac"
  },
  {
    "id": "fair",
    "name": "Fair",
    "color": "#f6c99d",
    "shadow": "#855136",
    "highlight": "#ffd0ac"
  },
  {
    "id": "golden",
    "name": "Golden",
    "color": "#f2ad63",
    "shadow": "#855136",
    "highlight": "#ffd0ac"
  },
  {
    "id": "medium_brown",
    "name": "Medium Brown",
    "color": "#9a5a36",
    "shadow": "#855136",
    "highlight": "#ffd0ac"
  },
  {
    "id": "porcelain",
    "name": "Porcelain",
    "color": "#f7d7c4",
    "shadow": "#855136",
    "highlight": "#ffd0ac"
  },
  {
    "id": "tan",
    "name": "Tan",
    "color": "#c98752",
    "shadow": "#855136",
    "highlight": "#ffd0ac"
  },
  {
    "id": "warm_beige",
    "name": "Warm Beige",
    "color": "#d9a06f",
    "shadow": "#855136",
    "highlight": "#ffd0ac"
  }
];

export const GENERATED_AVATAR_HAIR_STYLES = [
  {
    "id": "auburn_bob",
    "name": "Auburn Bob",
    "color": "#9a3412",
    "shadow": "#111827",
    "highlight": "#9a3412"
  },
  {
    "id": "auburn_crop",
    "name": "Auburn Crop",
    "color": "#9a3412",
    "shadow": "#111827",
    "highlight": "#9a3412"
  },
  {
    "id": "auburn_curls",
    "name": "Auburn Curls",
    "color": "#9a3412",
    "shadow": "#111827",
    "highlight": "#9a3412"
  },
  {
    "id": "auburn_ponytail",
    "name": "Auburn Ponytail",
    "color": "#9a3412",
    "shadow": "#111827",
    "highlight": "#9a3412"
  },
  {
    "id": "auburn_long_spikes",
    "name": "Auburn Long Spikes",
    "color": "#9a3412",
    "shadow": "#111827",
    "highlight": "#9a3412"
  },
  {
    "id": "auburn_short_spikes",
    "name": "Auburn Short Spikes",
    "color": "#9a3412",
    "shadow": "#111827",
    "highlight": "#9a3412"
  },
  {
    "id": "auburn_swept",
    "name": "Auburn Swept",
    "color": "#9a3412",
    "shadow": "#111827",
    "highlight": "#9a3412"
  },
  {
    "id": "black_bob",
    "name": "Black Bob",
    "color": "#111827",
    "shadow": "#111827",
    "highlight": "#111827"
  },
  {
    "id": "black_crop",
    "name": "Black Crop",
    "color": "#111827",
    "shadow": "#111827",
    "highlight": "#111827"
  },
  {
    "id": "black_curls",
    "name": "Black Curls",
    "color": "#111827",
    "shadow": "#111827",
    "highlight": "#111827"
  },
  {
    "id": "black_ponytail",
    "name": "Black Ponytail",
    "color": "#111827",
    "shadow": "#111827",
    "highlight": "#111827"
  },
  {
    "id": "black_long_spikes",
    "name": "Black Long Spikes",
    "color": "#111827",
    "shadow": "#111827",
    "highlight": "#111827"
  },
  {
    "id": "black_short_spikes",
    "name": "Black Short Spikes",
    "color": "#111827",
    "shadow": "#111827",
    "highlight": "#111827"
  },
  {
    "id": "black_swept",
    "name": "Black Swept",
    "color": "#111827",
    "shadow": "#111827",
    "highlight": "#111827"
  },
  {
    "id": "blonde_bob",
    "name": "Blonde Bob",
    "color": "#facc15",
    "shadow": "#111827",
    "highlight": "#facc15"
  },
  {
    "id": "blonde_crop",
    "name": "Blonde Crop",
    "color": "#facc15",
    "shadow": "#111827",
    "highlight": "#facc15"
  },
  {
    "id": "blonde_curls",
    "name": "Blonde Curls",
    "color": "#facc15",
    "shadow": "#111827",
    "highlight": "#facc15"
  },
  {
    "id": "blonde_ponytail",
    "name": "Blonde Ponytail",
    "color": "#facc15",
    "shadow": "#111827",
    "highlight": "#facc15"
  },
  {
    "id": "blonde_long_spikes",
    "name": "Blonde Long Spikes",
    "color": "#facc15",
    "shadow": "#111827",
    "highlight": "#facc15"
  },
  {
    "id": "blonde_short_spikes",
    "name": "Blonde Short Spikes",
    "color": "#facc15",
    "shadow": "#111827",
    "highlight": "#facc15"
  },
  {
    "id": "blonde_swept",
    "name": "Blonde Swept",
    "color": "#facc15",
    "shadow": "#111827",
    "highlight": "#facc15"
  },
  {
    "id": "brown_bob",
    "name": "Brown Bob",
    "color": "#7c2d12",
    "shadow": "#111827",
    "highlight": "#7c2d12"
  },
  {
    "id": "brown_crop",
    "name": "Brown Crop",
    "color": "#7c2d12",
    "shadow": "#111827",
    "highlight": "#7c2d12"
  },
  {
    "id": "brown_curls",
    "name": "Brown Curls",
    "color": "#7c2d12",
    "shadow": "#111827",
    "highlight": "#7c2d12"
  },
  {
    "id": "brown_ponytail",
    "name": "Brown Ponytail",
    "color": "#7c2d12",
    "shadow": "#111827",
    "highlight": "#7c2d12"
  },
  {
    "id": "brown_long_spikes",
    "name": "Brown Long Spikes",
    "color": "#7c2d12",
    "shadow": "#111827",
    "highlight": "#7c2d12"
  },
  {
    "id": "brown_short_spikes",
    "name": "Brown Short Spikes",
    "color": "#7c2d12",
    "shadow": "#111827",
    "highlight": "#7c2d12"
  },
  {
    "id": "brown_swept",
    "name": "Brown Swept",
    "color": "#7c2d12",
    "shadow": "#111827",
    "highlight": "#7c2d12"
  },
  {
    "id": "pink_bob",
    "name": "Pink Bob",
    "color": "#ec4899",
    "shadow": "#111827",
    "highlight": "#ec4899"
  },
  {
    "id": "pink_crop",
    "name": "Pink Crop",
    "color": "#ec4899",
    "shadow": "#111827",
    "highlight": "#ec4899"
  },
  {
    "id": "pink_curls",
    "name": "Pink Curls",
    "color": "#ec4899",
    "shadow": "#111827",
    "highlight": "#ec4899"
  },
  {
    "id": "pink_ponytail",
    "name": "Pink Ponytail",
    "color": "#ec4899",
    "shadow": "#111827",
    "highlight": "#ec4899"
  },
  {
    "id": "pink_long_spikes",
    "name": "Pink Long Spikes",
    "color": "#ec4899",
    "shadow": "#111827",
    "highlight": "#ec4899"
  },
  {
    "id": "pink_short_spikes",
    "name": "Pink Short Spikes",
    "color": "#ec4899",
    "shadow": "#111827",
    "highlight": "#ec4899"
  },
  {
    "id": "pink_swept",
    "name": "Pink Swept",
    "color": "#ec4899",
    "shadow": "#111827",
    "highlight": "#ec4899"
  },
  {
    "id": "red_bob",
    "name": "Red Bob",
    "color": "#dc2626",
    "shadow": "#111827",
    "highlight": "#dc2626"
  },
  {
    "id": "red_crop",
    "name": "Red Crop",
    "color": "#dc2626",
    "shadow": "#111827",
    "highlight": "#dc2626"
  },
  {
    "id": "red_curls",
    "name": "Red Curls",
    "color": "#dc2626",
    "shadow": "#111827",
    "highlight": "#dc2626"
  },
  {
    "id": "red_ponytail",
    "name": "Red Ponytail",
    "color": "#dc2626",
    "shadow": "#111827",
    "highlight": "#dc2626"
  },
  {
    "id": "red_long_spikes",
    "name": "Red Long Spikes",
    "color": "#dc2626",
    "shadow": "#111827",
    "highlight": "#dc2626"
  },
  {
    "id": "red_short_spikes",
    "name": "Red Short Spikes",
    "color": "#dc2626",
    "shadow": "#111827",
    "highlight": "#dc2626"
  },
  {
    "id": "red_swept",
    "name": "Red Swept",
    "color": "#dc2626",
    "shadow": "#111827",
    "highlight": "#dc2626"
  },
  {
    "id": "teal_bob",
    "name": "Teal Bob",
    "color": "#0f766e",
    "shadow": "#111827",
    "highlight": "#0f766e"
  },
  {
    "id": "teal_crop",
    "name": "Teal Crop",
    "color": "#0f766e",
    "shadow": "#111827",
    "highlight": "#0f766e"
  },
  {
    "id": "teal_curls",
    "name": "Teal Curls",
    "color": "#0f766e",
    "shadow": "#111827",
    "highlight": "#0f766e"
  },
  {
    "id": "teal_ponytail",
    "name": "Teal Ponytail",
    "color": "#0f766e",
    "shadow": "#111827",
    "highlight": "#0f766e"
  },
  {
    "id": "teal_long_spikes",
    "name": "Teal Long Spikes",
    "color": "#0f766e",
    "shadow": "#111827",
    "highlight": "#0f766e"
  },
  {
    "id": "teal_short_spikes",
    "name": "Teal Short Spikes",
    "color": "#0f766e",
    "shadow": "#111827",
    "highlight": "#0f766e"
  },
  {
    "id": "teal_swept",
    "name": "Teal Swept",
    "color": "#0f766e",
    "shadow": "#111827",
    "highlight": "#0f766e"
  }
];

export const GENERATED_AVATAR_FACE_STYLES = [
  {
    "id": "focused",
    "name": "Focused"
  },
  {
    "id": "happy",
    "name": "Happy"
  },
  {
    "id": "surprise",
    "name": "Surprise"
  }
];

export const GENERATED_AVATAR_OUTFITS = [
  {
    "id": "explorers_jacket",
    "name": "Explorers Jacket",
    "color": "#7c3aed",
    "shadow": "#3b0764",
    "accent": "#fbbf24",
    "trim": "#111827",
    "colorClass": "bg-violet-600"
  },
  {
    "id": "archivist_vest",
    "name": "Archivist Vest",
    "color": "#0f766e",
    "shadow": "#134e4a",
    "accent": "#ccfbf1",
    "trim": "#111827",
    "colorClass": "bg-teal-700"
  },
  {
    "id": "artist_apron",
    "name": "Artist Apron",
    "color": "#b45309",
    "shadow": "#78350f",
    "accent": "#fde68a",
    "trim": "#111827",
    "colorClass": "bg-amber-700"
  },
  {
    "id": "dream_painter",
    "name": "Dream Painter",
    "color": "#2563eb",
    "shadow": "#1e3a8a",
    "accent": "#bfdbfe",
    "trim": "#111827",
    "colorClass": "bg-blue-600"
  },
  {
    "id": "explorer",
    "name": "Explorer",
    "color": "#db2777",
    "shadow": "#831843",
    "accent": "#fef3c7",
    "trim": "#111827",
    "colorClass": "bg-pink-600"
  },
  {
    "id": "gallery_guard",
    "name": "Gallery Guard",
    "color": "#475569",
    "shadow": "#0f172a",
    "accent": "#86efac",
    "trim": "#111827",
    "colorClass": "bg-slate-600"
  },
  {
    "id": "herbologist",
    "name": "Herbologist",
    "color": "#7c3aed",
    "shadow": "#3b0764",
    "accent": "#fbbf24",
    "trim": "#111827",
    "colorClass": "bg-emerald-700"
  },
  {
    "id": "inventors_apron",
    "name": "Inventors Apron",
    "color": "#0f766e",
    "shadow": "#134e4a",
    "accent": "#ccfbf1",
    "trim": "#111827",
    "colorClass": "bg-cyan-700"
  },
  {
    "id": "magic_explorer",
    "name": "Magic Explorer",
    "color": "#b45309",
    "shadow": "#78350f",
    "accent": "#fde68a",
    "trim": "#111827",
    "colorClass": "bg-rose-700"
  },
  {
    "id": "masonry_overalls",
    "name": "Masonry Overalls",
    "color": "#2563eb",
    "shadow": "#1e3a8a",
    "accent": "#bfdbfe",
    "trim": "#111827",
    "colorClass": "bg-indigo-700"
  },
  {
    "id": "mystic_robe",
    "name": "Mystic Robe",
    "color": "#db2777",
    "shadow": "#831843",
    "accent": "#fef3c7",
    "trim": "#111827",
    "colorClass": "bg-lime-700"
  },
  {
    "id": "painted_hoodie",
    "name": "Painted Hoodie",
    "color": "#475569",
    "shadow": "#0f172a",
    "accent": "#86efac",
    "trim": "#111827",
    "colorClass": "bg-fuchsia-700"
  },
  {
    "id": "painters_smock",
    "name": "Painters Smock",
    "color": "#7c3aed",
    "shadow": "#3b0764",
    "accent": "#fbbf24",
    "trim": "#111827",
    "colorClass": "bg-orange-700"
  }
];

export const GENERATED_AVATAR_HELD_OBJECTS = [
  {
    "id": "brush",
    "name": "Brush",
    "color": "#7c2d12",
    "accent": "#facc15"
  },
  {
    "id": "camera",
    "name": "Camera",
    "color": "#f8fafc",
    "accent": "#38bdf8"
  },
  {
    "id": "coin_pouch",
    "name": "Coin Pouch",
    "color": "#334155",
    "accent": "#fbbf24"
  },
  {
    "id": "compass",
    "name": "Compass",
    "color": "#7dd3fc",
    "accent": "#f0abfc"
  },
  {
    "id": "crystal",
    "name": "Crystal",
    "color": "#f5d0a9",
    "accent": "#ef4444"
  },
  {
    "id": "crystal_staff",
    "name": "Crystal Staff",
    "color": "#64748b",
    "accent": "#bae6fd"
  },
  {
    "id": "flower",
    "name": "Flower",
    "color": "#7c2d12",
    "accent": "#facc15"
  },
  {
    "id": "herb",
    "name": "Herb",
    "color": "#f8fafc",
    "accent": "#38bdf8"
  },
  {
    "id": "hourglass",
    "name": "Hourglass",
    "color": "#334155",
    "accent": "#fbbf24"
  },
  {
    "id": "key",
    "name": "Key",
    "color": "#7dd3fc",
    "accent": "#f0abfc"
  },
  {
    "id": "magnifying_glass",
    "name": "Magnifying Glass",
    "color": "#f5d0a9",
    "accent": "#ef4444"
  },
  {
    "id": "mallet",
    "name": "Mallet",
    "color": "#64748b",
    "accent": "#bae6fd"
  },
  {
    "id": "map",
    "name": "Map",
    "color": "#7c2d12",
    "accent": "#facc15"
  },
  {
    "id": "palette",
    "name": "Palette",
    "color": "#f8fafc",
    "accent": "#38bdf8"
  },
  {
    "id": "pencil",
    "name": "Pencil",
    "color": "#334155",
    "accent": "#fbbf24"
  },
  {
    "id": "potion",
    "name": "Potion",
    "color": "#7dd3fc",
    "accent": "#f0abfc"
  },
  {
    "id": "quill",
    "name": "Quill",
    "color": "#f5d0a9",
    "accent": "#ef4444"
  },
  {
    "id": "scroll",
    "name": "Scroll",
    "color": "#64748b",
    "accent": "#bae6fd"
  },
  {
    "id": "shield",
    "name": "Shield",
    "color": "#7c2d12",
    "accent": "#facc15"
  },
  {
    "id": "spellbook",
    "name": "Spellbook",
    "color": "#f8fafc",
    "accent": "#38bdf8"
  },
  {
    "id": "star_staff",
    "name": "Star Staff",
    "color": "#334155",
    "accent": "#fbbf24"
  },
  {
    "id": "telescope",
    "name": "Telescope",
    "color": "#7dd3fc",
    "accent": "#f0abfc"
  },
  {
    "id": "torch",
    "name": "Torch",
    "color": "#f5d0a9",
    "accent": "#ef4444"
  },
  {
    "id": "wand",
    "name": "Wand",
    "color": "#64748b",
    "accent": "#bae6fd"
  },
  {
    "id": "wrench",
    "name": "Wrench",
    "color": "#7c2d12",
    "accent": "#facc15"
  }
];

export const GENERATED_AVATAR_LAYER_MAP = {
  "skinToneId": {
    "amber": "./public/images/avatar-layers/generated/normalized/Asset.skin/amber.png",
    "deep_brown": "./public/images/avatar-layers/generated/normalized/Asset.skin/deep_brown.png",
    "fair": "./public/images/avatar-layers/generated/normalized/Asset.skin/fair.png",
    "golden": "./public/images/avatar-layers/generated/normalized/Asset.skin/golden.png",
    "medium_brown": "./public/images/avatar-layers/generated/normalized/Asset.skin/medium_brown.png",
    "porcelain": "./public/images/avatar-layers/generated/normalized/Asset.skin/porcelain.png",
    "tan": "./public/images/avatar-layers/generated/normalized/Asset.skin/tan.png",
    "warm_beige": "./public/images/avatar-layers/generated/normalized/Asset.skin/warm_beige.png"
  },
  "hairStyleId": {
    "auburn_bob": "./public/images/avatar-layers/generated/normalized/Asset.Hair/Auburn/Bob.Auburn.png",
    "auburn_crop": "./public/images/avatar-layers/generated/normalized/Asset.Hair/Auburn/Crop.Auburn.png",
    "auburn_curls": "./public/images/avatar-layers/generated/normalized/Asset.Hair/Auburn/curls.Auburn.png",
    "auburn_ponytail": "./public/images/avatar-layers/generated/normalized/Asset.Hair/Auburn/ponytail.Auburn.png",
    "auburn_long_spikes": "./public/images/avatar-layers/generated/normalized/Asset.Hair/Auburn/spikeslong.Auburn.png",
    "auburn_short_spikes": "./public/images/avatar-layers/generated/normalized/Asset.Hair/Auburn/spikesshort.auburn.png",
    "auburn_swept": "./public/images/avatar-layers/generated/normalized/Asset.Hair/Auburn/swept.auburn.png",
    "black_bob": "./public/images/avatar-layers/generated/normalized/Asset.Hair/black/Bob.black.png",
    "black_crop": "./public/images/avatar-layers/generated/normalized/Asset.Hair/black/crop.black.png",
    "black_curls": "./public/images/avatar-layers/generated/normalized/Asset.Hair/black/curls.black.png",
    "black_ponytail": "./public/images/avatar-layers/generated/normalized/Asset.Hair/black/ponytail.black.png",
    "black_long_spikes": "./public/images/avatar-layers/generated/normalized/Asset.Hair/black/spikeslong.black.png",
    "black_short_spikes": "./public/images/avatar-layers/generated/normalized/Asset.Hair/black/spikesshort.black.png",
    "black_swept": "./public/images/avatar-layers/generated/normalized/Asset.Hair/black/swept.black.png",
    "blonde_bob": "./public/images/avatar-layers/generated/normalized/Asset.Hair/blonde/Bob.blonde.png",
    "blonde_crop": "./public/images/avatar-layers/generated/normalized/Asset.Hair/blonde/crop.blonde.png",
    "blonde_curls": "./public/images/avatar-layers/generated/normalized/Asset.Hair/blonde/curls.blonde.png",
    "blonde_ponytail": "./public/images/avatar-layers/generated/normalized/Asset.Hair/blonde/ponytail.blonde.png",
    "blonde_long_spikes": "./public/images/avatar-layers/generated/normalized/Asset.Hair/blonde/spikeslong.blonde.png",
    "blonde_short_spikes": "./public/images/avatar-layers/generated/normalized/Asset.Hair/blonde/spikesshort.blonde.png",
    "blonde_swept": "./public/images/avatar-layers/generated/normalized/Asset.Hair/blonde/swept.blonde.png",
    "brown_bob": "./public/images/avatar-layers/generated/normalized/Asset.Hair/brown/Bob.brown.png",
    "brown_crop": "./public/images/avatar-layers/generated/normalized/Asset.Hair/brown/crop.brown.png",
    "brown_curls": "./public/images/avatar-layers/generated/normalized/Asset.Hair/brown/curls.brown.png",
    "brown_ponytail": "./public/images/avatar-layers/generated/normalized/Asset.Hair/brown/ponytail.brown.png",
    "brown_long_spikes": "./public/images/avatar-layers/generated/normalized/Asset.Hair/brown/spikeslong.brown.png",
    "brown_short_spikes": "./public/images/avatar-layers/generated/normalized/Asset.Hair/brown/spikesshort.brown.png",
    "brown_swept": "./public/images/avatar-layers/generated/normalized/Asset.Hair/brown/swept.brown.png",
    "pink_bob": "./public/images/avatar-layers/generated/normalized/Asset.Hair/pink/bob.pink.png",
    "pink_crop": "./public/images/avatar-layers/generated/normalized/Asset.Hair/pink/crop.pink.png",
    "pink_curls": "./public/images/avatar-layers/generated/normalized/Asset.Hair/pink/curls.pink.png",
    "pink_ponytail": "./public/images/avatar-layers/generated/normalized/Asset.Hair/pink/ponytail.pink.png",
    "pink_long_spikes": "./public/images/avatar-layers/generated/normalized/Asset.Hair/pink/spikeslong.pink.png",
    "pink_short_spikes": "./public/images/avatar-layers/generated/normalized/Asset.Hair/pink/spikesshort.pink.png",
    "pink_swept": "./public/images/avatar-layers/generated/normalized/Asset.Hair/pink/swept.pink.png",
    "red_bob": "./public/images/avatar-layers/generated/normalized/Asset.Hair/red/bob.red.png",
    "red_crop": "./public/images/avatar-layers/generated/normalized/Asset.Hair/red/crop.red.png",
    "red_curls": "./public/images/avatar-layers/generated/normalized/Asset.Hair/red/curls.red.png",
    "red_ponytail": "./public/images/avatar-layers/generated/normalized/Asset.Hair/red/ponytail.red.png",
    "red_long_spikes": "./public/images/avatar-layers/generated/normalized/Asset.Hair/red/spikeslong.red.png",
    "red_short_spikes": "./public/images/avatar-layers/generated/normalized/Asset.Hair/red/spikesshort.red.png",
    "red_swept": "./public/images/avatar-layers/generated/normalized/Asset.Hair/red/swept.red.png",
    "teal_bob": "./public/images/avatar-layers/generated/normalized/Asset.Hair/teal/bob.teal.png",
    "teal_crop": "./public/images/avatar-layers/generated/normalized/Asset.Hair/teal/crop.teal.png",
    "teal_curls": "./public/images/avatar-layers/generated/normalized/Asset.Hair/teal/curls.teal.png",
    "teal_ponytail": "./public/images/avatar-layers/generated/normalized/Asset.Hair/teal/ponytail.teal.png",
    "teal_long_spikes": "./public/images/avatar-layers/generated/normalized/Asset.Hair/teal/spikeslong.teal.png",
    "teal_short_spikes": "./public/images/avatar-layers/generated/normalized/Asset.Hair/teal/spikesshort.teal.png",
    "teal_swept": "./public/images/avatar-layers/generated/normalized/Asset.Hair/teal/swept.teal.png"
  },
  "faceId": {
    "focused_amber": "./public/images/avatar-layers/generated/normalized/Asset.Faces/Focused/Focused.amber.png",
    "focused_deep_brown": "./public/images/avatar-layers/generated/normalized/Asset.Faces/Focused/Focused.Deep Brown.png",
    "focused_fair": "./public/images/avatar-layers/generated/normalized/Asset.Faces/Focused/Focused.Fair.png",
    "focused_golden": "./public/images/avatar-layers/generated/normalized/Asset.Faces/Focused/Focused.golden.png",
    "focused_medium_brown": "./public/images/avatar-layers/generated/normalized/Asset.Faces/Focused/Focused.Medium Brown.png",
    "focused_porcelain": "./public/images/avatar-layers/generated/normalized/Asset.Faces/Focused/Focused.Porcelain.png",
    "focused_tan": "./public/images/avatar-layers/generated/normalized/Asset.Faces/Focused/Focused.Tan.png",
    "focused_warm_beige": "./public/images/avatar-layers/generated/normalized/Asset.Faces/Focused/Focused.Warm Beige.png",
    "happy_amber": "./public/images/avatar-layers/generated/normalized/Asset.Faces/Happy/Happy.amber.png",
    "happy_deep_brown": "./public/images/avatar-layers/generated/normalized/Asset.Faces/Happy/happy.deep brown.png",
    "happy_fair": "./public/images/avatar-layers/generated/normalized/Asset.Faces/Happy/Happy.Fair.png",
    "happy_golden": "./public/images/avatar-layers/generated/normalized/Asset.Faces/Happy/Happy.golden.png",
    "happy_medium_brown": "./public/images/avatar-layers/generated/normalized/Asset.Faces/Happy/Happy.medium brown.png",
    "happy_porcelain": "./public/images/avatar-layers/generated/normalized/Asset.Faces/Happy/Happy.Porcelain.png",
    "happy_tan": "./public/images/avatar-layers/generated/normalized/Asset.Faces/Happy/Happy.tan.png",
    "happy_warm_beige": "./public/images/avatar-layers/generated/normalized/Asset.Faces/Happy/Happy.Warm beige.png",
    "surprise_amber": "./public/images/avatar-layers/generated/normalized/Asset.Faces/Surprise/Surprise.amber.png",
    "surprise_deep_brown": "./public/images/avatar-layers/generated/normalized/Asset.Faces/Surprise/Surprise.deep brown.png",
    "surprise_fair": "./public/images/avatar-layers/generated/normalized/Asset.Faces/Surprise/Surprise.Fair.png",
    "surprise_golden": "./public/images/avatar-layers/generated/normalized/Asset.Faces/Surprise/Surprise.golden.png",
    "surprise_medium_brown": "./public/images/avatar-layers/generated/normalized/Asset.Faces/Surprise/Surprise.medium brown.png",
    "surprise_porcelain": "./public/images/avatar-layers/generated/normalized/Asset.Faces/Surprise/Surprise.Porcelain.png",
    "surprise_tan": "./public/images/avatar-layers/generated/normalized/Asset.Faces/Surprise/Surprise.tan.png",
    "surprise_warm_beige": "./public/images/avatar-layers/generated/normalized/Asset.Faces/Surprise/Surprise.warm beige.png"
  },
  "outfitId": {
    "explorers_jacket": "./public/images/avatar-layers/generated/normalized/Asset.outfit/Outfit. Explorers Jacket.png",
    "archivist_vest": "./public/images/avatar-layers/generated/normalized/Asset.outfit/Outfit.Archivist Vest.png",
    "artist_apron": "./public/images/avatar-layers/generated/normalized/Asset.outfit/Outfit.Artist apron.png",
    "dream_painter": "./public/images/avatar-layers/generated/normalized/Asset.outfit/Outfit.Dream Painter.png",
    "explorer": "./public/images/avatar-layers/generated/normalized/Asset.outfit/Outfit.Explorer.png",
    "gallery_guard": "./public/images/avatar-layers/generated/normalized/Asset.outfit/Outfit.Gallery Guard.png",
    "herbologist": "./public/images/avatar-layers/generated/normalized/Asset.outfit/Outfit.Herbologist.png",
    "inventors_apron": "./public/images/avatar-layers/generated/normalized/Asset.outfit/Outfit.Inventors apron.png",
    "magic_explorer": "./public/images/avatar-layers/generated/normalized/Asset.outfit/Outfit.Magic Explorer.png",
    "masonry_overalls": "./public/images/avatar-layers/generated/normalized/Asset.outfit/Outfit.Masonry overalls.png",
    "mystic_robe": "./public/images/avatar-layers/generated/normalized/Asset.outfit/Outfit.Mystic Robe.png",
    "painted_hoodie": "./public/images/avatar-layers/generated/normalized/Asset.outfit/Outfit.Painted Hoodie.png",
    "painters_smock": "./public/images/avatar-layers/generated/normalized/Asset.outfit/Outfit.Painters smock.png"
  },
  "heldObjectId": {
    "brush": "./public/images/avatar-layers/generated/normalized/asset.object/object.brush.png",
    "camera": "./public/images/avatar-layers/generated/normalized/asset.object/object.camera.png",
    "coin_pouch": "./public/images/avatar-layers/generated/normalized/asset.object/object.coinpouch.png",
    "compass": "./public/images/avatar-layers/generated/normalized/asset.object/object.compass.png",
    "crystal": "./public/images/avatar-layers/generated/normalized/asset.object/object.crystal.png",
    "crystal_staff": "./public/images/avatar-layers/generated/normalized/asset.object/object.crystalstaff.png",
    "flower": "./public/images/avatar-layers/generated/normalized/asset.object/object.flower.png",
    "herb": "./public/images/avatar-layers/generated/normalized/asset.object/object.herb.png",
    "hourglass": "./public/images/avatar-layers/generated/normalized/asset.object/object.hourglass.png",
    "key": "./public/images/avatar-layers/generated/normalized/asset.object/object.key.png",
    "magnifying_glass": "./public/images/avatar-layers/generated/normalized/asset.object/object.magnifying glass.png",
    "mallet": "./public/images/avatar-layers/generated/normalized/asset.object/object.mallet.png",
    "map": "./public/images/avatar-layers/generated/normalized/asset.object/object.map.png",
    "palette": "./public/images/avatar-layers/generated/normalized/asset.object/object.palette.png",
    "pencil": "./public/images/avatar-layers/generated/normalized/asset.object/object.pencil.png",
    "potion": "./public/images/avatar-layers/generated/normalized/asset.object/object.potion.png",
    "quill": "./public/images/avatar-layers/generated/normalized/asset.object/object.quill.png",
    "scroll": "./public/images/avatar-layers/generated/normalized/asset.object/object.scroll.png",
    "shield": "./public/images/avatar-layers/generated/normalized/asset.object/object.shield.png",
    "spellbook": "./public/images/avatar-layers/generated/normalized/asset.object/object.spellbook.png",
    "star_staff": "./public/images/avatar-layers/generated/normalized/asset.object/object.starstaff.png",
    "telescope": "./public/images/avatar-layers/generated/normalized/asset.object/object.telescope.png",
    "torch": "./public/images/avatar-layers/generated/normalized/asset.object/object.torch.png",
    "wand": "./public/images/avatar-layers/generated/normalized/asset.object/object.wand.png",
    "wrench": "./public/images/avatar-layers/generated/normalized/asset.object/object.wrench.png"
  },
  "accessoryId": {}
};

export const GENERATED_AVATAR_ASSET_REPORT = {
  "totalPngs": 111,
  "dimensionCounts": {
    "1024x1536": 21,
    "1058x1487": 10,
    "1086x1448": 42,
    "1254x1254": 37,
    "724x2172": 1
  }
};
