from pathlib import Path
import json

from PIL import Image


PROJECT_ROOT = Path(__file__).resolve().parent.parent
ASSET_ROOT = PROJECT_ROOT / "public/images/avatar-layers/generated/normalized"
OUTPUT_PATH = PROJECT_ROOT / "data/AvatarAssetBounds.generated.ts"


def to_public_path(path: Path) -> str:
    return f"./{path.relative_to(PROJECT_ROOT).as_posix()}"


def get_alpha_bounds(path: Path):
    with Image.open(path) as image:
        rgba_image = image.convert("RGBA")
        alpha_bbox = rgba_image.getchannel("A").getbbox()
        natural_width, natural_height = rgba_image.size

    if not alpha_bbox:
        return None

    left, top, right, bottom = alpha_bbox
    return {
        "naturalWidth": natural_width,
        "naturalHeight": natural_height,
        "left": left,
        "top": top,
        "width": right - left,
        "height": bottom - top,
    }


def main():
    bounds_by_url = {}

    for path in sorted(ASSET_ROOT.rglob("*.png")):
        bounds = get_alpha_bounds(path)
        if bounds:
            bounds_by_url[to_public_path(path)] = bounds

    source = "\n".join([
        "// This file is generated by scripts/generate-avatar-asset-bounds.py.",
        "// Rerun after avatar layer PNGs are regenerated.",
        "",
        "export interface AvatarAssetBoundsManifestEntry {",
        "  naturalWidth: number;",
        "  naturalHeight: number;",
        "  left: number;",
        "  top: number;",
        "  width: number;",
        "  height: number;",
        "}",
        "",
        "export const AVATAR_ASSET_BOUNDS_BY_URL: Record<string, AvatarAssetBoundsManifestEntry> = ",
        json.dumps(bounds_by_url, indent=2, sort_keys=True),
        ";",
        "",
    ])

    OUTPUT_PATH.write_text(source, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH} with {len(bounds_by_url)} asset bounds.")


if __name__ == "__main__":
    main()
